dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
notifications:
  slack:
    secure: PfE8J43XNko28Y8VWzGfP3CwUM91CZq9XPf1Cw6br+yaLydbBSAazwarvcKAp74HeEBGdUYpTPDTTqWHGrtdozGQREWhsgCNzDNlJld27QdentMb3V0YzhZIXJ7LbFTiD1l/MTy3pG1Ny1heMe53TD7u2Xpuzqf2z+lpXHbNY9PXvVq9P86m4ICxQCF5YZvBCKzB77ruTVhOo4tM8dfAjrItnWGHeyZeI/KoUj8X8UeBogc3737pBw+LwmcOa6yZIJHyljfWzfqtK6BMtEsk+LJo91OR8yOtL4Qpei9b3RupVITN0qKVWyYNThtDKeRtcA62u9vwx3Cno7AMPDZwokeXCmvLOSgawwlcwu/pTTZLJ9aCJGGgk88WLvbSZzMXe0ZAEmr8N7vvAuzS6lmTnMykeCji2aSPICE74UfgkafbGh+jJ/rLYr3PVyiRkchyD5z9UXVn8d8fm6EXvoUakrm2l5pTGF7uc1ur0aue1LGAbLeikn0jCF2IUN2kPMpMU9Vu+NCQrF75UhKIh4U4oW3LJ2qNp40V3w2goK80m8TSyH+bxPnPP0qKK1NysM0mFfZThy34vb+t7mH9y1o6rGsqWLTfDabBqWwex35dT19rxsV2MBn6g9EE7jElwFFPPAL0R5vCzJd+uRrXBZ4okOVR1COIXFLO2/w3/4ymwqY=
